### ISSUE TITLE
Spaces in pack names only work with the optional argument (0/1)

### ISSUE THREAD

**Issue by vvambo** [Baertram/AddonSelector#2]
This is less of an actual bug, but more how functions work and I think it is enough to clearly mention it in the description

**Comment by vvambo** [comment]
It would be nice though if the first argument is not a single digit number (1 or 2) that it would just use 1 for global and keep everything from the argument as second argument

**Comment by Baertram** [comment]
> It would be nice though if the first argument is not a single digit number (1 or 2) that it would just use 1 for global and keep everything from the argument as second argument

Described how it works in your other issue report

**Comment by Baertram** [comment]
> This is less of an actual bug, but more how functions work and I think it is enough to clearly mention it in the description

All I could do is accept "" as surrounding string identifiers so it will accept spaces in pack names.
I'll have a look, but usually packs should not contain spaces. They should be short and created with _ or - instead of spaces, to ease the saving and loading.

**Comment by Baertram** [comment]
Added a function to detect " ", ' ' and \" \' escaped (double)quotes so params can use spaces.
That way 1st param could be a character name now too, if 2nd param is provided with a packname.
Or 1st param could be a packname, or 1 for global or 2 for current character name

**Comment by vvambo** [comment]
Was about to open this up again. But I still miss that I am on "save char pack" setting and try to use `/asl <packnameonly`
