### ISSUE TITLE
Ommiting the optional argument locks into currently selected "pack realm"

### ISSUE THREAD

**Issue by vvambo** [Baertram/AddonSelector#3]
Until now I haven't used character packages but I created one to test and once I selected this I couldn't  select my global packages when ommiting the argument to select character or global (2/1)  but had to use it.

My feeling  (and the beta description) said that global would be the default and because I might not know whether I am on a character or global package there should be a default. 

using `/asl #Addontest`
![image](https://github.com/user-attachments/assets/3d3d1db7-072e-42ea-b876-ea26827c5dae)
![image](https://github.com/user-attachments/assets/8f11f658-8e9f-4ff7-94b1-a1b948c3cbce)
![image](https://github.com/user-attachments/assets/59bf14dc-b958-4a8b-9a5f-134a196fde0f)

Nice to see that case sensitivity is not necessary. I'm a bit confused why it shows an ID instead of the character name there...

The opposite test: from my Character pack "necro pack" I could load Chraracter pack "neroCraft" with ` /asl Necrocraft`

**Comment by Baertram** [comment]
The /asl command's default will be the global OR the character packs depending on your settings "Save character packs" ON/OFF
ON -> Character packs are loaded for the currently logged in character
Off -> Global packs are loaded

ON but using /asl 1 packName -> Global packName will be loaded
ON but using /asl 2 packName -> Character pack packName will be loaded for the currently logged in character

Might be buggy here and there, have to test it.

**Comment by vvambo** [comment]
Oh, well I misunderstood how it is supposed to work then!
Gonna test again to make sure there is confusing behaviour. 
Yes that's it.

 Definitely needs a sentence in the description that the default changes with that setting.
