### ISSUE TITLE
Strange behaviour with the logout feature

### ISSUE THREAD

**Issue by vvambo** [Baertram/AddonSelector#5]
1. try: selected a character package to load at logout and then selected another global one as "active" (no realodui) and after logout and login I ended up with the old active pack - not the one selected for logout (char pack)

2. try: selected a global pack for logout, active was another global pack --> logout+login--> selected logout pack was active...

**Comment by Baertram** [comment]
> 1. try: selected a character package to load at logout and then selected another global one as "active" (no realodui) and after logout and login I ended up with the old active pack - not the one selected for logout (char pack)
> 
@vvambo Does that happen if you select the character pack for logout and then logout without changing the active packs too?
Or does it load the selected character pack properly then?

**Comment by vvambo** [comment]
Tested it again and it just seems to not load a character pack for logout.

~~After creating a second character subset and encountering #6 I couldn't even select the logout option anymore.
Could not select ANY logout option as a matter of fact... Looks like I've broken something :D~~ This was due to wrong LibScrollableMenu version

**Comment by vvambo** [comment]
After reseting my SavedVars and retrying I could not recreate the behaviour. 
Char pack is selected no matter whether I selected another pack, whether char save was on or off.
