### ISSUE TITLE
Wrong Character Pack name in select menu if a change is made from a different  char

### ISSUE THREAD

**Issue by vvambo** [Baertram/AddonSelector#6]
I created character packs for testing on 2 characters A and B
To differentiate I each activated a specific addon on each pack. I did this change logged into character B and overwrote the pack of character A which (after a reloadUI) resulted in a weird behaviour of having char B listed twice in the *Select* menu.

![image](https://github.com/user-attachments/assets/93c9f7ac-3b81-4da6-82a9-c55b1710f84b)
It is still showing the correct name for *Selected*:
![image](https://github.com/user-attachments/assets/a9dddace-4595-48d4-82f1-d33d468e7ae8)

Pretty minor issue though

**Comment by vvambo** [comment]
~~This stays consistent on other (3rd) characters as well.
After this I also could not select ANY of the logout options anymore, global or char pack~~

**Comment by Baertram** [comment]
To rebuild this, what do I have to do? @vvambo 
1. Login with Char A
2. Set AS settings to save character packs
3. Save Pack1 of currently logged in Char A
4. Logout
5. Login with Char B
6. Save Pack2 of currently logged in Char B
7. Change the pack1 of currently NOT logged in Char A
8. Reload UI
Now I see Character B's name twice in the character list and Character A is gone?

**Comment by vvambo** [comment]
I think I forgot to test this again after getting the correct LibScrollableMenu version.
So:
1-5.  as above
6. (might be optional)
7. Select any random package 
8. and choose overwrite in the submenu of Char A's Pack1
9. Char A's name changes to Char B  --> 2 x Char B entry
10. Reloadui
 ->persistent 2 Char B entries
 
 I also noticed I cannot delete the "fake" Char B entry

**Comment by Baertram** [comment]
Ah I see, thanks.
Think I know what is going on

**Comment by Baertram** [comment]
Found it, and should be fixed now
